name: Node.js CI

on:
  push:
    branches: ['**']
  # pull_request:
  #   branches: ["master", "new-feature"]

jobs:
  setup-inicial:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Inicial
        uses: actions/setup-node@v3
        with:
          cache: "npm"
      - run: npm install
      - run: npx prettier . --write
      - run: npx prettier . --check

  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Jest + Lint
        uses: actions/setup-node@v3
        with:
          cache: "npm"
      - run: npm install
      - run: npm test
      - run: npm run lint

  # deploy:
  #   runs-on: ubuntu-latest
  #   if:  github.ref == 'refs/heads/master' 

  #   needs: [setup-inicial, test]
    
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Build e Deploy
  #       uses: actions/setup-node@v3
  #     - run: npm install     #instala dependências
  #     - run:  npm run build  #build
  #     - run: npx netlify-cli deploy --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --prod  #deploy para netlify
